[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Joshua Shrader <jshrader83@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.1"
image = "0.23"
crossbeam = "0.7"
num_cpus = "1.13"
